### ISSUE TITLE
Data not updating on uchiwa

### ISSUE THREAD

**Issue by roopchandy** [palourde/uchiwa-docs#6]
tail /var/log/uchiwa.log

{"timestamp":"2016-08-16T16:20:48.383757351Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: dial tcp 127.0.0.1:4567: getsockopt: connection refused"}
{"timestamp":"2016-08-16T16:20:48.383788209Z","level":"warn","message":"Connection failed to the datacenter l27.0.0.1"}
{"timestamp":"2016-08-16T16:20:58.383530169Z","level":"info","message":"Updating the datacenter l27.0.0.1"}
{"timestamp":"2016-08-16T16:21:23.492293864Z","level":"warn","message":"Loading the configuration file /etc/sensu/uchiwa.json"}
{"timestamp":"2016-08-16T16:21:23.492697533Z","level":"warn","message":"**_###  Uchiwa is now listening on 0.0.0.0:3000"}_**
{"timestamp":"2016-08-16T16:21:23.492718244Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:22:13.493065172Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-08-16T16:22:13.493120059Z","level":"warn","message":"Connection failed to the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:22:23.493377472Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:23:13.493615446Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-08-16T16:23:13.493673682Z","level":"warn","message":"Connection failed to the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:23:13.493691103Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:24:03.493865749Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-08-16T16:24:03.493942798Z","level":"warn","message":"Connection failed to the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:24:03.493961955Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:24:53.49416452Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-08-16T16:24:53.494219404Z","level":"warn","message":"Connection failed to the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:24:53.494237385Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:25:43.494436037Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-08-16T16:25:43.494485368Z","level":"warn","message":"Connection failed to the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:25:43.494514048Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:26:33.494695529Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-08-16T16:26:33.494751502Z","level":"warn","message":"Connection failed to the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:26:33.494775166Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T16:27:23.495000897Z","level":"warn","message":"GET http://127.0.0.1:4567/stashes returned: Get http://127.0.0.1:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-08-16T16:27:23.495054979Z","level":"warn","message":"Connection failed to the datacenter sensu-test1"}
## {"timestamp":"2016-08-16T16:27:23.495072396Z","level":"info","message":"Updating the datacenter sensu-test1"}

-rw-r--r--   1 root      root           0 Aug 16 16:21 uchiwa.err

---

 cat /etc/sensu/uchiwa.json
{
  "sensu": [
    {
      "name": "sensu-test1",
      "host": "127.0.0.1",
      "port": 4567,
      "timeout": 50,
      "user": "sensu",
      "pass": "secret"
    }
  ],
  "uchiwa": {
    "host": "0.0.0.0",
    "port": 3000,
    "refresh": 10
  }
## }

I am running a standalone configuration.  

Error: Uchiva is having trouble updating its data. Try refresh page if issue persists

OS: UBUNTU 14.04

**Comment by roopchandy** [comment]
tail uchiwa.log
{"timestamp":"2016-08-16T17:52:53.260550484Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:53:03.260576201Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:53:13.260590097Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:53:23.260582876Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:53:33.260585401Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:53:43.260568988Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:53:53.260563314Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:54:03.260598699Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:54:13.260567743Z","level":"info","message":"Updating the datacenter sensu-test1"}
{"timestamp":"2016-08-16T17:54:23.26054254Z","level":"info","message":"Updating the datacenter sensu-test1"}


Now i see this ..still no data on uchiwa dashboard

**Comment by mhelmetag** [comment]
You may get more help if you post to the [main uchiwa repo](https://github.com/sensu/uchiwa).

**Comment by palourde** [comment]
Hi @roopchandy 

If you still face any issue, please open an issue on the [uchiwa repository](https://github.com/sensu/uchiwa) as stated above.

Thanks!
